In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785579011.966790    7338 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1785579012.131016    7338 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1785579014.003679    7338 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='str')

In [5]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

Min max scaler

In [6]:
X_min = X.min()
X_max = X.max()

scaled  = (X - X_min)/(X_max - X_min + 1e-8)

In [7]:
scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [8]:
X_train, X_test, y_train, y_test = train_test_split(scaled, y, test_size=0.2, random_state=42,stratify=y)

In [9]:
model = keras.Sequential([
    layers.InputLayer(shape=(X_train.shape[1],)),
    layers.Dense(8, activation= 'relu'),
    layers.Dense(1, activation= 'sigmoid')
])

W0000 00:00:1785579016.786922    7338 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

In [10]:
model.compile(optimizer= 'sgd' , loss="binary_crossentropy" , metrics= ['accuracy'])

In [11]:
history = model.fit(X_train.values, y_train.values, validation_data=(X_test.values,y_test.values), epochs= 100, batch_size= 4,verbose= 1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7347 - val_accuracy: 0.5000 - val_loss: 0.6809
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.7328 - val_accuracy: 0.5000 - val_loss: 0.6804
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7312 - val_accuracy: 0.5000 - val_loss: 0.6799
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7297 - val_accuracy: 0.2500 - val_loss: 0.6794
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5000 - loss: 0.7280 - val_accuracy: 0.2500 - val_loss: 0.6790
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7268 - val_accuracy: 0.2500 - val_loss: 0.6785
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7246 - val_accuracy: 0.2500 - val_loss: 0.6781
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7239 - val_accuracy: 0.2500 - val_loss: 0.6778
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7223 - val_accuracy: 0.2500 - val_loss: 0.6773
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.7215 - val_accuracy: 0.2500 - val_loss: 0.6767
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7198 - val_accuracy: 0.2500 - val_loss: 0.6762
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7198 - val_accuracy: 0.2500 - val_loss: 0.6756
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7170 - val_accuracy: 0.2500 - val_loss: 0.6750
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7167 - val_accuracy: 0.2500 - val_loss: 0.6745
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7149 - val_accuracy: 0.2500 - val_loss: 0.6740
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7145 - val_accuracy: 0.2500 - val_loss: 0.6735
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7134 - val_accuracy: 0.2500 - val_loss: 0.6730
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7125 - val_accuracy: 0.2500 - val_loss: 0.6726
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7113 - val_accuracy: 0.2500 - val_loss: 0.6721
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.7107 - val_accuracy: 0.2500 - val_loss: 0.6717
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.7092 - val_accuracy: 0.2500 - val_loss: 0.6712
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.7090 - val_accuracy: 0.2500 - val_loss: 0.6708
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.7080 - val_accuracy: 0.2500 - val_loss: 0.6704
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.7070 - val_accuracy: 0.5000 - val_loss: 0.6700
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7063 - val_accuracy: 0.7500 - val_loss: 0.6696
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7055 - val_accuracy: 0.7500 - val_loss: 0.6692
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7044 - val_accuracy: 0.7500 - val_loss: 0.6689
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7036 - val_accuracy: 0.7500 - val_loss: 0.6685
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.7033 - val_accuracy: 0.7500 - val_loss: 0.6682
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7028 - val_accuracy: 0.7500 - val_loss: 0.6678
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5000 - loss: 0.7022 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5000 - loss: 0.7014 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5000 - loss: 0.7022 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.7002 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.6991 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.6989 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6980 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5000 - loss: 0.6979 - val_accuracy: 0.7500 - val_loss: 0.6677
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6975 - val_accuracy: 0.7500 - val_loss: 0.6676
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5833 - loss: 0.6968 - val_accuracy: 0.7500 - val_loss: 0.6678
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6959 - val_accuracy: 0.7500 - val_loss: 0.6680
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6958 - val_accuracy: 0.7500 - val_loss: 0.6682
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6949 - val_accuracy: 0.7500 - val_loss: 0.6684
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6947 - val_accuracy: 0.7500 - val_loss: 0.6686
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6944 - val_accuracy: 0.7500 - val_loss: 0.6688
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6934 - val_accuracy: 0.7500 - val_loss: 0.6690
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6930 - val_accuracy: 0.7500 - val_loss: 0.6691
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6929 - val_accuracy: 0.7500 - val_loss: 0.6693
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6926 - val_accuracy: 0.7500 - val_loss: 0.6695
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6931 - val_accuracy: 0.7500 - val_loss: 0.6696
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6918 - val_accuracy: 0.7500 - val_loss: 0.6698
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6914 - val_accuracy: 0.7500 - val_loss: 0.6700
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5833 - loss: 0.6910 - val_accuracy: 0.7500 - val_loss: 0.6701
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6900 - val_accuracy: 0.7500 - val_loss: 0.6703
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6900 - val_accuracy: 0.7500 - val_loss: 0.6704
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6897 - val_accuracy: 0.7500 - val_loss: 0.6706
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.6902 - val_accuracy: 0.7500 - val_loss: 0.6707
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6885 - val_accuracy: 0.7500 - val_loss: 0.6708
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.6884 - val_accuracy: 0.7500 - val_loss: 0.6710
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6895 - val_accuracy: 0.7500 - val_loss: 0.6711
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6880 - val_accuracy: 0.7500 - val_loss: 0.6713
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6874 - val_accuracy: 0.7500 - val_loss: 0.6714
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6866 - val_accuracy: 0.7500 - val_loss: 0.6715
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6868 - val_accuracy: 0.7500 - val_loss: 0.6717
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6864 - val_accuracy: 0.7500 - val_loss: 0.6718
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6857 - val_accuracy: 0.7500 - val_loss: 0.6719
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6859 - val_accuracy: 0.7500 - val_loss: 0.6720
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6868 - val_accuracy: 0.7500 - val_loss: 0.6721
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6851 - val_accuracy: 0.7500 - val_loss: 0.6722
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6848 - val_accuracy: 0.7500 - val_loss: 0.6724
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6844 - val_accuracy: 0.7500 - val_loss: 0.6725
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6842 - val_accuracy: 0.7500 - val_loss: 0.6726
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6834 - val_accuracy: 0.7500 - val_loss: 0.6727
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6836 - val_accuracy: 0.7500 - val_loss: 0.6728
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6827 - val_accuracy: 0.7500 - val_loss: 0.6729
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6825 - val_accuracy: 0.7500 - val_loss: 0.6730
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6826 - val_accuracy: 0.7500 - val_loss: 0.6731
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6824 - val_accuracy: 0.7500 - val_loss: 0.6732
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6819 - val_accuracy: 0.7500 - val_loss: 0.6733
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6817 - val_accuracy: 0.7500 - val_loss: 0.6734
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6824 - val_accuracy: 0.7500 - val_loss: 0.6735
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6820 - val_accuracy: 0.7500 - val_loss: 0.6735
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6823 - val_accuracy: 0.7500 - val_loss: 0.6736
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6805 - val_accuracy: 0.7500 - val_loss: 0.6737
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6811 - val_accuracy: 0.7500 - val_loss: 0.6738
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6795 - val_accuracy: 0.7500 - val_loss: 0.6739
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6797 - val_accuracy: 0.7500 - val_loss: 0.6739
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6802 - val_accuracy: 0.7500 - val_loss: 0.6740
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6790 - val_accuracy: 0.7500 - val_loss: 0.6741
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6787 - val_accuracy: 0.7500 - val_loss: 0.6741
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6786 - val_accuracy: 0.7500 - val_loss: 0.6742
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6782 - val_accuracy: 0.7500 - val_loss: 0.6743
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6780 - val_accuracy: 0.7500 - val_loss: 0.6743
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6773 - val_accuracy: 0.7500 - val_loss: 0.6744
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6774 - val_accuracy: 0.7500 - val_loss: 0.6744
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6767 - val_accuracy: 0.7500 - val_loss: 0.6745
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6768 - val_accuracy: 0.7500 - val_loss: 0.6745
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6766 - val_accuracy: 0.7500 - val_loss: 0.6746
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6759 - val_accuracy: 0.7500 - val_loss: 0.6745
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6763 - val_accuracy: 0.7500 - val_loss: 0.6744