In [1]:
from idlelib import history

import tensorflow as tf
import numpy as np
import pandas as pd
from keras.src.metrics.accuracy_metrics import accuracy
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [3]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [4]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [5]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

Min max scaler

In [6]:
X_min = X.min()
X_max = X.max()

scaled  = (X - X_min)/(X_max - X_min + 1e-8)

In [7]:
scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [8]:
X_train, X_test, y_train, y_test = train_test_split(scaled, y, test_size=0.2, random_state=42,stratify=y)

In [9]:
model = keras.Sequential([
    layers.InputLayer(shape=(X_train.shape[1],)),
    layers.Dense(8, activation= 'relu'),
    layers.Dense(1, activation= 'sigmoid')
])

In [10]:
model.compile(optimizer= 'sgd' , loss="binary_crossentropy" , metrics= ['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [11]:
history = model.fit(X_train.values, y_train.values, validation_data=(X_test.values,y_test.values), epochs= 100, batch_size= 4,verbose= 1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5000 - loss: 0.6907 - val_accuracy: 1.0000 - val_loss: 0.5739
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6857 - val_accuracy: 0.7500 - val_loss: 0.5730
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6848 - val_accuracy: 0.7500 - val_loss: 0.5722
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6786 - val_accuracy: 0.7500 - val_loss: 0.5714
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6782 - val_accuracy: 0.7500 - val_loss: 0.5707
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6734 - val_accuracy: 0.7500 - val_loss: 0.5701
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5833 - loss: 0.6704 - val_accuracy: 0.7500 - val_loss: 0.5698
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6679 - val_accuracy: 0.7500 - val_loss: 0.5696
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6655 - val_accuracy: 0.7500 - val_loss: 0.5693
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6667 - loss: 0.6624 - val_accuracy: 0.7500 - val_loss: 0.5691
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6610 - val_accuracy: 0.7500 - val_loss: 0.5689
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6579 - val_accuracy: 0.7500 - val_loss: 0.5687
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6558 - val_accuracy: 0.7500 - val_loss: 0.5685
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6539 - val_accuracy: 0.7500 - val_loss: 0.5683
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6530 - val_accuracy: 0.7500 - val_loss: 0.5682
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6532 - val_accuracy: 0.7500 - val_loss: 0.5680
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6492 - val_accuracy: 0.7500 - val_loss: 0.5677
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6470 - val_accuracy: 0.7500 - val_loss: 0.5675
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6453 - val_accuracy: 0.7500 - val_loss: 0.5673
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5833 - loss: 0.6479 - val_accuracy: 0.7500 - val_loss: 0.5671
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5833 - loss: 0.6435 - val_accuracy: 0.7500 - val_loss: 0.5670
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5833 - loss: 0.6418 - val_accuracy: 0.7500 - val_loss: 0.5670
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6398 - val_accuracy: 0.7500 - val_loss: 0.5669
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.6667 - loss: 0.6388 - val_accuracy: 0.7500 - val_loss: 0.5668
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6667 - loss: 0.6384 - val_accuracy: 0.7500 - val_loss: 0.5668
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7500 - loss: 0.6390 - val_accuracy: 0.7500 - val_loss: 0.5668
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.6350 - val_accuracy: 0.7500 - val_loss: 0.5668
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.6352 - val_accuracy: 0.7500 - val_loss: 0.5668
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7500 - loss: 0.6329 - val_accuracy: 0.7500 - val_loss: 0.5667
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7500 - loss: 0.6329 - val_accuracy: 0.7500 - val_loss: 0.5666
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.6337 - val_accuracy: 0.7500 - val_loss: 0.5666
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6308 - val_accuracy: 0.7500 - val_loss: 0.5665
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6290 - val_accuracy: 0.7500 - val_loss: 0.5664
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6289 - val_accuracy: 0.7500 - val_loss: 0.5663
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6274 - val_accuracy: 0.7500 - val_loss: 0.5662
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6263 - val_accuracy: 0.7500 - val_loss: 0.5661
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6261 - val_accuracy: 0.7500 - val_loss: 0.5660
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6246 - val_accuracy: 0.7500 - val_loss: 0.5659
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.6244 - val_accuracy: 0.7500 - val_loss: 0.5657
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6230 - val_accuracy: 0.7500 - val_loss: 0.5656
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6231 - val_accuracy: 0.7500 - val_loss: 0.5654
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6223 - val_accuracy: 0.7500 - val_loss: 0.5653
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6215 - val_accuracy: 0.7500 - val_loss: 0.5650
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6205 - val_accuracy: 0.7500 - val_loss: 0.5649
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6200 - val_accuracy: 0.7500 - val_loss: 0.5646
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6201 - val_accuracy: 0.7500 - val_loss: 0.5643
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6192 - val_accuracy: 0.7500 - val_loss: 0.5641
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6182 - val_accuracy: 0.7500 - val_loss: 0.5637
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6201 - val_accuracy: 0.7500 - val_loss: 0.5634
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6174 - val_accuracy: 0.7500 - val_loss: 0.5632
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6163 - val_accuracy: 0.7500 - val_loss: 0.5628
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6159 - val_accuracy: 0.7500 - val_loss: 0.5625
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6149 - val_accuracy: 0.7500 - val_loss: 0.5622
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6144 - val_accuracy: 0.7500 - val_loss: 0.5618
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6132 - val_accuracy: 0.7500 - val_loss: 0.5615
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6130 - val_accuracy: 0.7500 - val_loss: 0.5613
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6153 - val_accuracy: 0.7500 - val_loss: 0.5609
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6114 - val_accuracy: 0.7500 - val_loss: 0.5605
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6118 - val_accuracy: 0.7500 - val_loss: 0.5601
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6122 - val_accuracy: 0.7500 - val_loss: 0.5599
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6102 - val_accuracy: 0.7500 - val_loss: 0.5595
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6114 - val_accuracy: 0.7500 - val_loss: 0.5592
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6085 - val_accuracy: 0.7500 - val_loss: 0.5588
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6115 - val_accuracy: 0.7500 - val_loss: 0.5583
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6074 - val_accuracy: 0.7500 - val_loss: 0.5579
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6076 - val_accuracy: 0.7500 - val_loss: 0.5575
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6073 - val_accuracy: 0.7500 - val_loss: 0.5571
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6060 - val_accuracy: 0.7500 - val_loss: 0.5567
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.6051 - val_accuracy: 0.7500 - val_loss: 0.5563
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6052 - val_accuracy: 0.7500 - val_loss: 0.5559
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6038 - val_accuracy: 0.7500 - val_loss: 0.5555
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.6039 - val_accuracy: 0.7500 - val_loss: 0.5550
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6039 - val_accuracy: 0.7500 - val_loss: 0.5545
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6031 - val_accuracy: 0.7500 - val_loss: 0.5541
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6015 - val_accuracy: 0.7500 - val_loss: 0.5536
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6036 - val_accuracy: 0.7500 - val_loss: 0.5532
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6009 - val_accuracy: 0.7500 - val_loss: 0.5527
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.5999 - val_accuracy: 0.7500 - val_loss: 0.5523
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6003 - val_accuracy: 0.7500 - val_loss: 0.5518
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7500 - loss: 0.5998 - val_accuracy: 0.7500 - val_loss: 0.5513
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6010 - val_accuracy: 0.7500 - val_loss: 0.5509
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6003 - val_accuracy: 0.7500 - val_loss: 0.5504
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5970 - val_accuracy: 0.7500 - val_loss: 0.5499
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5969 - val_accuracy: 0.7500 - val_loss: 0.5495
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5966 - val_accuracy: 0.7500 - val_loss: 0.5491
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.5963 - val_accuracy: 0.7500 - val_loss: 0.5486
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5946 - val_accuracy: 0.7500 - val_loss: 0.5482
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5948 - val_accuracy: 0.7500 - val_loss: 0.5477
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5935 - val_accuracy: 0.7500 - val_loss: 0.5472
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5930 - val_accuracy: 0.7500 - val_loss: 0.5469
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8333 - loss: 0.5929 - val_accuracy: 0.7500 - val_loss: 0.5463
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5917 - val_accuracy: 0.7500 - val_loss: 0.5459
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8333 - loss: 0.5941 - val_accuracy: 0.7500 - val_loss: 0.5456
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5906 - val_accuracy: 0.7500 - val_loss: 0.5450
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5909 - val_accuracy: 0.7500 - val_loss: 0.5445
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.5898 - val_accuracy: 0.7500 - val_loss: 0.5440
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5903 - val_accuracy: 0.7500 - val_loss: 0.5436
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5896 - val_accuracy: 0.7500 - val_loss: 0.5432
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5884 - val_accuracy: 0.7500 - val_loss: 0.5427
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5878 - val_accuracy: 0.7500 - val_loss: 0.5421

In [11]:
history_full = model.fit(X_train.values, y_train.values, validation_data=(X_test.values, y_test.values), batch_size=len(X_train), epochs=100, verbose= 1)

//gradient desent optimiser

history = model.fit(X_train.values, y_train.values, validation_data=(X_test.values,y_test.values),batch_size= 1 , epochs= 100, verbose=1) // stochastic gradent desent (SGD)

// upperone is mini batch gradient