In [23]:
from idlelib import history

import tensorflow as tf
import numpy as np
import pandas as pd
from keras.src.metrics.accuracy_metrics import accuracy
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

In [24]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [25]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [26]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [27]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

Min max scaler

In [28]:
X_min = X.min()
X_max = X.max()

scaled  = (X - X_min)/(X_max - X_min + 1e-8)

In [29]:
scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [30]:
X_train, X_test, y_train, y_test = train_test_split(scaled, y, test_size=0.2, random_state=42,stratify=y)

In [31]:
model = keras.Sequential([
    layers.InputLayer(shape=(X_train.shape[1],)),
    layers.Dense(8, activation= 'relu'),
    layers.Dense(1, activation= 'sigmoid')
])

In [32]:
model.compile(optimizer= 'sgd' , loss="binary_crossentropy" , metrics= ['accuracy'])

In [33]:
history = model.fit(X_train.values, y_train.values, validation_data=(X_test.values,y_test.values), epochs= 100, batch_size= 4,verbose= 1)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6475 - val_accuracy: 0.5000 - val_loss: 0.6430
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.6474 - val_accuracy: 0.5000 - val_loss: 0.6422
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.6466 - val_accuracy: 0.5000 - val_loss: 0.6414
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5000 - loss: 0.6461 - val_accuracy: 0.5000 - val_loss: 0.6405
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.5000 - loss: 0.6445 - val_accuracy: 0.5000 - val_loss: 0.6397
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.6472 - val_accuracy: 0.5000 - val_loss: 0.6389
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.6438 - val_accuracy: 0.5000 - val_loss: 0.6382
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6437 - val_accuracy: 0.5000 - val_loss: 0.6374
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5000 - loss: 0.6451 - val_accuracy: 0.5000 - val_loss: 0.6366
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6430 - val_accuracy: 0.5000 - val_loss: 0.6359
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6431 - val_accuracy: 0.5000 - val_loss: 0.6352
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6404 - val_accuracy: 0.5000 - val_loss: 0.6345
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6401 - val_accuracy: 0.5000 - val_loss: 0.6338
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6392 - val_accuracy: 0.7500 - val_loss: 0.6330
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6385 - val_accuracy: 0.7500 - val_loss: 0.6323
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5833 - loss: 0.6382 - val_accuracy: 0.7500 - val_loss: 0.6316
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6397 - val_accuracy: 0.7500 - val_loss: 0.6310
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6371 - val_accuracy: 0.7500 - val_loss: 0.6303
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.5833 - loss: 0.6360 - val_accuracy: 0.7500 - val_loss: 0.6296
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6350 - val_accuracy: 0.7500 - val_loss: 0.6289
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6352 - val_accuracy: 0.7500 - val_loss: 0.6283
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5833 - loss: 0.6369 - val_accuracy: 0.7500 - val_loss: 0.6276
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6333 - val_accuracy: 0.7500 - val_loss: 0.6270
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6338 - val_accuracy: 0.7500 - val_loss: 0.6263
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6325 - val_accuracy: 0.7500 - val_loss: 0.6257
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6315 - val_accuracy: 0.7500 - val_loss: 0.6253
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6315 - val_accuracy: 1.0000 - val_loss: 0.6247
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6303 - val_accuracy: 1.0000 - val_loss: 0.6242
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6297 - val_accuracy: 1.0000 - val_loss: 0.6236
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.6667 - loss: 0.6311 - val_accuracy: 1.0000 - val_loss: 0.6230
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6296 - val_accuracy: 1.0000 - val_loss: 0.6227
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6291 - val_accuracy: 1.0000 - val_loss: 0.6222
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6281 - val_accuracy: 1.0000 - val_loss: 0.6216
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6278 - val_accuracy: 1.0000 - val_loss: 0.6211
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6272 - val_accuracy: 1.0000 - val_loss: 0.6205
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.6667 - loss: 0.6265 - val_accuracy: 1.0000 - val_loss: 0.6200
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6260 - val_accuracy: 1.0000 - val_loss: 0.6194
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6667 - loss: 0.6255 - val_accuracy: 1.0000 - val_loss: 0.6191
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6249 - val_accuracy: 1.0000 - val_loss: 0.6185
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6241 - val_accuracy: 1.0000 - val_loss: 0.6180
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6239 - val_accuracy: 1.0000 - val_loss: 0.6177
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6226 - val_accuracy: 1.0000 - val_loss: 0.6171
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6227 - val_accuracy: 1.0000 - val_loss: 0.6166
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6221 - val_accuracy: 1.0000 - val_loss: 0.6160
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6218 - val_accuracy: 1.0000 - val_loss: 0.6155
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6212 - val_accuracy: 1.0000 - val_loss: 0.6149
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.6223 - val_accuracy: 1.0000 - val_loss: 0.6146
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6198 - val_accuracy: 1.0000 - val_loss: 0.6141
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6195 - val_accuracy: 1.0000 - val_loss: 0.6135
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6188 - val_accuracy: 1.0000 - val_loss: 0.6130
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6667 - loss: 0.6204 - val_accuracy: 1.0000 - val_loss: 0.6124
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.6177 - val_accuracy: 1.0000 - val_loss: 0.6121
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6174 - val_accuracy: 1.0000 - val_loss: 0.6115
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6173 - val_accuracy: 1.0000 - val_loss: 0.6110
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6188 - val_accuracy: 1.0000 - val_loss: 0.6104
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6155 - val_accuracy: 1.0000 - val_loss: 0.6101
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7500 - loss: 0.6156 - val_accuracy: 1.0000 - val_loss: 0.6096
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.6144 - val_accuracy: 1.0000 - val_loss: 0.6090
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6139 - val_accuracy: 1.0000 - val_loss: 0.6085
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6129 - val_accuracy: 1.0000 - val_loss: 0.6079
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6147 - val_accuracy: 1.0000 - val_loss: 0.6074
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6125 - val_accuracy: 1.0000 - val_loss: 0.6068
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6110 - val_accuracy: 1.0000 - val_loss: 0.6063
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7500 - loss: 0.6114 - val_accuracy: 1.0000 - val_loss: 0.6057
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6099 - val_accuracy: 1.0000 - val_loss: 0.6054
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6101 - val_accuracy: 1.0000 - val_loss: 0.6048
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7500 - loss: 0.6088 - val_accuracy: 1.0000 - val_loss: 0.6042
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6086 - val_accuracy: 1.0000 - val_loss: 0.6037
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6084 - val_accuracy: 1.0000 - val_loss: 0.6031
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.6078 - val_accuracy: 1.0000 - val_loss: 0.6025
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6076 - val_accuracy: 1.0000 - val_loss: 0.6021
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6065 - val_accuracy: 1.0000 - val_loss: 0.6015
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6090 - val_accuracy: 1.0000 - val_loss: 0.6009
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6055 - val_accuracy: 1.0000 - val_loss: 0.6004
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.6043 - val_accuracy: 1.0000 - val_loss: 0.5998
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.6047 - val_accuracy: 1.0000 - val_loss: 0.5992
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6037 - val_accuracy: 1.0000 - val_loss: 0.5986
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6049 - val_accuracy: 1.0000 - val_loss: 0.5981
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6026 - val_accuracy: 1.0000 - val_loss: 0.5976
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6019 - val_accuracy: 1.0000 - val_loss: 0.5970
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6035 - val_accuracy: 1.0000 - val_loss: 0.5965
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.6002 - val_accuracy: 1.0000 - val_loss: 0.5959
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6023 - val_accuracy: 1.0000 - val_loss: 0.5953
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6001 - val_accuracy: 1.0000 - val_loss: 0.5947
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9167 - loss: 0.5992 - val_accuracy: 1.0000 - val_loss: 0.5942
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7500 - loss: 0.5990 - val_accuracy: 1.0000 - val_loss: 0.5936
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.5986 - val_accuracy: 1.0000 - val_loss: 0.5931
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.6002 - val_accuracy: 1.0000 - val_loss: 0.5925
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.5970 - val_accuracy: 1.0000 - val_loss: 0.5920
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5968 - val_accuracy: 1.0000 - val_loss: 0.5914
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.9167 - loss: 0.5962 - val_accuracy: 1.0000 - val_loss: 0.5908
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.5957 - val_accuracy: 1.0000 - val_loss: 0.5902
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5975 - val_accuracy: 1.0000 - val_loss: 0.5896
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9167 - loss: 0.5939 - val_accuracy: 1.0000 - val_loss: 0.5890
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9167 - loss: 0.5928 - val_accuracy: 1.0000 - val_loss: 0.5885
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8333 - loss: 0.5928 - val_accuracy: 1.0000 - val_loss: 0.5879
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.5916 - val_accuracy: 1.0000 - val_loss: 0.5873
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.5919 - val_accuracy: 1.0000 - val_loss: 0.5867
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8333 - loss: 0.5918 - val_accuracy: 1.0000 - val_loss: 0.5860
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8333 - loss: 0.5905 - val_accuracy: 1.0000 - val_loss: 0.5854