In [ ]:
import numpy as np
import  pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('qoute_dataset.csv')

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
quotes[0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [ ]:
quotes = quotes.str.lower()

In [ ]:
quotes[0]

'“the world as we have created it is a process of our thinking. it cannot be changed without changing our thinking.”'

In [ ]:
import string
translator = str.maketrans('','',string.punctuation)
quotes = quotes.apply(lambda x : x.translate(translator))

In [ ]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
vocab_size = 10000

tokenizer = Tokenizer(num_words= vocab_size)
tokenizer.fit_on_texts(quotes)

In [ ]:
word_index = tokenizer.word_index
print(len(word_index))

8978

In [ ]:
sentences = tokenizer.texts_to_sequences(quotes)

In [ ]:
X = []
y = []

for seq in sentences:
    for i in range(1, len(seq)):
        input_seq = seq[:i]
        output_seq = seq[i]
        X.append(input_seq)
        y.append(output_seq)

In [ ]:
len(X)

85271

In [ ]:
len(y)

85271

In [ ]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_pad = pad_sequences(X, maxlen = max_len, padding= 'pre')

In [ ]:
X_pad

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [ ]:
y = np.array(y)

In [ ]:
X_pad.shape

(85271, 745)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_onehot = to_categorical(y, num_classes= vocab_size )

In [ ]:
y_onehot.shape

(85271, 10000)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,SimpleRNN

In [ ]:
embedded_dim = 50
rnn_units = 128

In [ ]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedded_dim, input_length=max_len))
rnn_model.add(SimpleRNN(units = rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

In [ ]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedded_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [ ]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs = 100
batch_size = 128

In [ ]:
# hist_rnn = rnn_model.fit(
#     X_pad, y_onehot, epochs=epochs, batch_size=batch_size, verbose=1,validation_split=0.2
# )

In [ ]:
hist_lstm = lstm_model.fit(
    X_pad, y_onehot, epochs=epochs, batch_size=batch_size, verbose=1,validation_split=0.2
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 37s 60ms/step - accuracy: 0.0391 - loss: 6.7623 - val_accuracy: 0.0440 - val_loss: 6.7595
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.0545 - loss: 6.3393 - val_accuracy: 0.0579 - val_loss: 6.6770
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.0714 - loss: 6.1099 - val_accuracy: 0.0772 - val_loss: 6.5773
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.0912 - loss: 5.8916 - val_accuracy: 0.0901 - val_loss: 6.5253
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.1041 - loss: 5.7134 - val_accuracy: 0.0982 - val_loss: 6.5197
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.1134 - loss: 5.5549 - val_accuracy: 0.0993 - val_loss: 6.5253
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.1218 - loss: 5.4017 - val_accuracy: 0.1044 - val_loss: 6.5453
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1296 - loss: 5.2574 - val_accuracy: 0.1051 - val_loss: 6.5817
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1375 - loss: 5.1208 - val_accuracy: 0.1073 - val_loss: 6.6124
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1443 - loss: 4.9895 - val_accuracy: 0.1077 - val_loss: 6.6587
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 60ms/step - accuracy: 0.1507 - loss: 4.8636 - val_accuracy: 0.1072 - val_loss: 6.7071
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1578 - loss: 4.7398 - val_accuracy: 0.1102 - val_loss: 6.7576
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.1654 - loss: 4.6186 - val_accuracy: 0.1122 - val_loss: 6.8111
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.1744 - loss: 4.5005 - val_accuracy: 0.1105 - val_loss: 6.8628
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.1831 - loss: 4.3859 - val_accuracy: 0.1105 - val_loss: 6.9296
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 60ms/step - accuracy: 0.1949 - loss: 4.2736 - val_accuracy: 0.1103 - val_loss: 6.9926
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.2074 - loss: 4.1651 - val_accuracy: 0.1119 - val_loss: 7.0802
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2209 - loss: 4.0598 - val_accuracy: 0.1094 - val_loss: 7.1500
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.2331 - loss: 3.9590 - val_accuracy: 0.1101 - val_loss: 7.2222
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2475 - loss: 3.8630 - val_accuracy: 0.1101 - val_loss: 7.3039
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.2597 - loss: 3.7729 - val_accuracy: 0.1094 - val_loss: 7.3673
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.2732 - loss: 3.6866 - val_accuracy: 0.1097 - val_loss: 7.4589
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.2850 - loss: 3.6068 - val_accuracy: 0.1081 - val_loss: 7.5234
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.2977 - loss: 3.5295 - val_accuracy: 0.1088 - val_loss: 7.5981
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 60ms/step - accuracy: 0.3086 - loss: 3.4571 - val_accuracy: 0.1047 - val_loss: 7.6756
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.3184 - loss: 3.3888 - val_accuracy: 0.1062 - val_loss: 7.7557
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 43s 63ms/step - accuracy: 0.3288 - loss: 3.3236 - val_accuracy: 0.1056 - val_loss: 7.8232
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.3383 - loss: 3.2604 - val_accuracy: 0.1057 - val_loss: 7.8904
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.3479 - loss: 3.1988 - val_accuracy: 0.1025 - val_loss: 7.9642
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.3571 - loss: 3.1408 - val_accuracy: 0.1061 - val_loss: 8.0300
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.3675 - loss: 3.0854 - val_accuracy: 0.1040 - val_loss: 8.1017
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.3774 - loss: 3.0303 - val_accuracy: 0.1041 - val_loss: 8.1679
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.3848 - loss: 2.9795 - val_accuracy: 0.1008 - val_loss: 8.2274
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.3940 - loss: 2.9281 - val_accuracy: 0.1007 - val_loss: 8.2930
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.4016 - loss: 2.8777 - val_accuracy: 0.1022 - val_loss: 8.3607
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.4102 - loss: 2.8301 - val_accuracy: 0.1010 - val_loss: 8.4208
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.4192 - loss: 2.7816 - val_accuracy: 0.1001 - val_loss: 8.4818
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.4275 - loss: 2.7361 - val_accuracy: 0.0993 - val_loss: 8.5454
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.4361 - loss: 2.6921 - val_accuracy: 0.1012 - val_loss: 8.6058
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.4438 - loss: 2.6483 - val_accuracy: 0.0990 - val_loss: 8.6785
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.4511 - loss: 2.6065 - val_accuracy: 0.0953 - val_loss: 8.7354
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.4579 - loss: 2.5645 - val_accuracy: 0.0973 - val_loss: 8.7922
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 60ms/step - accuracy: 0.4644 - loss: 2.5258 - val_accuracy: 0.0964 - val_loss: 8.8480
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.4717 - loss: 2.4859 - val_accuracy: 0.0955 - val_loss: 8.9275
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.4805 - loss: 2.4479 - val_accuracy: 0.0946 - val_loss: 8.9893
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 60ms/step - accuracy: 0.4866 - loss: 2.4100 - val_accuracy: 0.0949 - val_loss: 9.0414
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.4943 - loss: 2.3735 - val_accuracy: 0.0940 - val_loss: 9.0947
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.4989 - loss: 2.3376 - val_accuracy: 0.0933 - val_loss: 9.1462
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.5052 - loss: 2.3028 - val_accuracy: 0.0919 - val_loss: 9.2120
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5124 - loss: 2.2690 - val_accuracy: 0.0940 - val_loss: 9.2704
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.5196 - loss: 2.2357 - val_accuracy: 0.0921 - val_loss: 9.3244
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.5252 - loss: 2.2029 - val_accuracy: 0.0912 - val_loss: 9.3935
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 43s 63ms/step - accuracy: 0.5309 - loss: 2.1715 - val_accuracy: 0.0918 - val_loss: 9.4400
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5373 - loss: 2.1398 - val_accuracy: 0.0900 - val_loss: 9.4959
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 60ms/step - accuracy: 0.5430 - loss: 2.1114 - val_accuracy: 0.0898 - val_loss: 9.5463
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.5476 - loss: 2.0815 - val_accuracy: 0.0877 - val_loss: 9.6068
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.5551 - loss: 2.0512 - val_accuracy: 0.0905 - val_loss: 9.6639
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5597 - loss: 2.0243 - val_accuracy: 0.0902 - val_loss: 9.7052
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.5666 - loss: 1.9950 - val_accuracy: 0.0880 - val_loss: 9.7558
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5713 - loss: 1.9679 - val_accuracy: 0.0884 - val_loss: 9.8138
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.5772 - loss: 1.9407 - val_accuracy: 0.0875 - val_loss: 9.8609
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5819 - loss: 1.9139 - val_accuracy: 0.0879 - val_loss: 9.9152
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 63ms/step - accuracy: 0.5869 - loss: 1.8879 - val_accuracy: 0.0855 - val_loss: 9.9755
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5922 - loss: 1.8638 - val_accuracy: 0.0861 - val_loss: 10.0206
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.5974 - loss: 1.8383 - val_accuracy: 0.0853 - val_loss: 10.0714
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.6019 - loss: 1.8139 - val_accuracy: 0.0853 - val_loss: 10.1409
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.6072 - loss: 1.7914 - val_accuracy: 0.0836 - val_loss: 10.1759
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.6132 - loss: 1.7664 - val_accuracy: 0.0845 - val_loss: 10.2194
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.6164 - loss: 1.7436 - val_accuracy: 0.0824 - val_loss: 10.2848
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.6212 - loss: 1.7219 - val_accuracy: 0.0835 - val_loss: 10.3384
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.6262 - loss: 1.6991 - val_accuracy: 0.0830 - val_loss: 10.3864
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.6308 - loss: 1.6788 - val_accuracy: 0.0817 - val_loss: 10.4419
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.6354 - loss: 1.6574 - val_accuracy: 0.0811 - val_loss: 10.4838
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.6393 - loss: 1.6356 - val_accuracy: 0.0826 - val_loss: 10.5425
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6431 - loss: 1.6167 - val_accuracy: 0.0814 - val_loss: 10.5903
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6469 - loss: 1.5961 - val_accuracy: 0.0844 - val_loss: 10.6461
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6530 - loss: 1.5760 - val_accuracy: 0.0823 - val_loss: 10.7003
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 34s 64ms/step - accuracy: 0.6555 - loss: 1.5571 - val_accuracy: 0.0811 - val_loss: 10.7344
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.6595 - loss: 1.5385 - val_accuracy: 0.0810 - val_loss: 10.7910
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.6651 - loss: 1.5196 - val_accuracy: 0.0783 - val_loss: 10.8562
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6668 - loss: 1.5039 - val_accuracy: 0.0790 - val_loss: 10.8901
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6728 - loss: 1.4838 - val_accuracy: 0.0796 - val_loss: 10.9425
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6750 - loss: 1.4659 - val_accuracy: 0.0772 - val_loss: 10.9906
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6801 - loss: 1.4482 - val_accuracy: 0.0786 - val_loss: 11.0266
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6825 - loss: 1.4318 - val_accuracy: 0.0799 - val_loss: 11.0832
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6874 - loss: 1.4144 - val_accuracy: 0.0781 - val_loss: 11.1376
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6898 - loss: 1.3989 - val_accuracy: 0.0777 - val_loss: 11.1705
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6933 - loss: 1.3824 - val_accuracy: 0.0777 - val_loss: 11.2157
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6971 - loss: 1.3675 - val_accuracy: 0.0776 - val_loss: 11.2752
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7006 - loss: 1.3514 - val_accuracy: 0.0775 - val_loss: 11.3272
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7043 - loss: 1.3364 - val_accuracy: 0.0762 - val_loss: 11.3713
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7073 - loss: 1.3219 - val_accuracy: 0.0765 - val_loss: 11.4129
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 34s 64ms/step - accuracy: 0.7105 - loss: 1.3057 - val_accuracy: 0.0747 - val_loss: 11.4715
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7138 - loss: 1.2923 - val_accuracy: 0.0749 - val_loss: 11.5167
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.7161 - loss: 1.2788 - val_accuracy: 0.0742 - val_loss: 11.5675
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.7189 - loss: 1.2648 - val_accuracy: 0.0758 - val_loss: 11.6234
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 61ms/step - accuracy: 0.7234 - loss: 1.2493 - val_accuracy: 0.0745 - val_loss: 11.6650
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.7256 - loss: 1.2362 - val_accuracy: 0.0744 - val_loss: 11.7064
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.7300 - loss: 1.2238 - val_accuracy: 0.0760 - val_loss: 11.7585
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 34s 63ms/step - accuracy: 0.7319 - loss: 1.2090 - val_accuracy: 0.0751 - val_loss: 11.7945

In [ ]:
lstm_model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word = {}
for word,index in word_index.items():
    index_to_word[index] = word

In [54]:
def predictor(model,text,tokenizer,max_len):

  text = text.lower()
  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [58]:
seed_text = "what are you"
next_word = predictor(lstm_model,seed_text,tokenizer,max_len)
print(next_word)

lurking

In [59]:
def generate_text(model,seed_text,num_words,tokenizer,max_len):
  text = seed_text
  for i in range(num_words):
    next_word = predictor(model,text,tokenizer,max_len)
    if next_word == "":
      break
    text += ' ' + next_word
  return text

In [60]:
seed_text = 'life is a'
generate_text = generate_text(lstm_model,seed_text,10,tokenizer,max_len)
print(generate_text)

life is a series of natural and spontaneous changes dont resist them that